export const browserstackTestAccounts = [
  'gem-1',
  'test-automation',
  'john-doe',
  'olive-5',
  'mary-14',
  'bond-03',
  'rock-64',
  'rock-3',
  'bond-02',
  'antman-kok357',
  'user-x01',
  'user-x01-1',
  'user-x02',
  'user-x04',
];
