# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)


match(type: "development")

match(type: "adhoc",
      app_identifier: "io.meta1.appbeta")

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "nativeapp.xcodeproj")
    build_app(workspace: "nativeapp.xcworkspace", scheme: "nativeapp")
    upload_to_testflight
  end
end

lane :nightly do
  name = "META1_" + Time.new.to_i.to_s + ".ipa"

  throw :MISSING_DIAWI_TOKEN if not ENV['DIAWI_TOKEN']
  throw :MISSING_SENTRY_TOKEN if not ENV['SENTRY_AUTH_TOKEN']
  
  setup_ci if ENV['CI']
  
  build_app(
    export_method: "ad-hoc",
    export_options: {
      provisioningProfiles: { 
        "io.meta1.appbeta" => "match AdHoc io.meta1.appbeta",
      }
    },
    output_directory: "../dist/",
    output_name: name
  )
  
  diawi(
    token: ENV["DIAWI_TOKEN"],
    file: "../dist/" + name
  )
  
  url = lane_context[SharedValues::UPLOADED_FILE_LINK_TO_DIAWI]
  sh("curl", "-s", "https://qrenco.de/" + url)
end
