name: BuildApkAndroid
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Install bundler and fastlane
        run: |
          sudo gem install bundler
          bundle install
      - name: Bump version
        run: |
          export ANDROID_ONLY=1
          yarn bump
      - name: Setup apk signning
        run: |
          echo "MYAPP_UPLOAD_STORE_FILE=debug.keystore" >> android/gradle.properties
          echo "MYAPP_UPLOAD_KEY_ALIAS=androiddebugkey" >> android/gradle.properties
          echo "MYAPP_UPLOAD_STORE_PASSWORD=android" >> android/gradle.properties
          echo "MYAPP_UPLOAD_KEY_PASSWORD=android" >> android/gradle.properties
      - name: Build Android Release
        env:
          NETWORK: ${{ secrets.NETWORK }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          ZENDESK_CHANNEL_KEY_ANDROID: ${{secrets.ZENDESK_CHANNEL_KEY_ANDROID}}
          ZENDESK_CHANNEL_KEY_IOS: ${{secrets.ZENDESK_CHANNEL_KEY_IOS}}
        run: |
          cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
