name: BuildApkAndroid
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          yarn install
      - name: Setup apk signning
        run: |
          echo "MYAPP_UPLOAD_STORE_FILE=debug.keystore" >> android/gradle.properties
          echo "MYAPP_UPLOAD_KEY_ALIAS=androiddebugkey" >> android/gradle.properties
          echo "MYAPP_UPLOAD_STORE_PASSWORD=android" >> android/gradle.properties
          echo "MYAPP_UPLOAD_KEY_PASSWORD=android" >> android/gradle.properties
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
