name: build-ios-app
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          yarn install
      - name: Install ruby dependencies
        run: |
          sudo get install cocoapods
          sudo gem install bundler
          bundle install
      - name: Install pod dependencies
        run: |
          cd ios
          pod install
      - name: Build and upload to Diawi
        run: |
          cd ios
          fastlane nightly
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          DIAWI_TOKEN: ${{ secrets.DIAWI_TOKEN }}
