name: build-ios-app
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Install ruby dependencies
        run: |
          sudo gem install cocoapods
          sudo gem install bundler
          bundle install
      - uses: actions/cache@v3
        id: cache-pods
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
              ${{ runner.os }}-pods-

      - name: Install pod dependencies
        run: |
          cd ios
          pod install
        # Try to patch out the automatic code signing
        # You probably can ignore it if this fails
        # Assuming you know what you're doing
      - name: Select manual code signing
        continue-on-error: true
        run: |
          git apply .github/workflows/ios-ci.patch
      - name: Build and upload to Diawi
        run: |
          cd ios
          fastlane nightly
        env:
          NETWORK: ${{ secrets.NETWORK }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          DIAWI_TOKEN: ${{ secrets.DIAWI_TOKEN }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          ZENDESK_CHANNEL_KEY_ANDROID: ${{secrets.ZENDESK_CHANNEL_KEY_ANDROID}}
          ZENDESK_CHANNEL_KEY_IOS: ${{secrets.ZENDESK_CHANNEL_KEY_IOS}}
      - name: Get Diawi URL and QR Code
        run: |
          echo ============================
          echo "Diawi Url: "
          cat /tmp/url
          echo "Qr code Url:"
          echo "https://www.diawi.com/qrcode/link/$(cat /tmp/url | awk -F/ '{print $4}')"
          echo ============================
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: |
            dist/**/*.ipa
            dist/**/*.zip
