name: build-ios-app
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          yarn install
      - name: Install ruby dependencies
        run: |
          sudo gem install cocoapods
          sudo gem install bundler
          bundle install
      - uses: actions/cache@v3
        id: cache-pods
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
              ${{ runner.os }}-pods-

      - name: Install pod dependencies
        if: steps.cache-pods.outputs.cache-hit != 'true'
        run: |
          cd ios
          pod install
      - name: Build and upload to Diawi
        run: |
          cd ios
          fastlane nightly
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          DIAWI_TOKEN: ${{ secrets.DIAWI_TOKEN }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT }}
      - name: Get Diawi URL and QR Code
        run: |
          echo ============================
          echo "Diawi Url: "
          cat /tmp/url
          echo "Qr code Url:"
          echo "https://www.diawi.com/qrcode/link/$(cat /tmp/url | awk -F/ '{print $4}')"
          echo ============================
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-build 
          path: |
            dist/**/*.ipa
            dist/**/*.zip
